steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 
  'us-east4-docker.pkg.dev/${PROJECT_ID}/imgs/${_SERVICE_NAME}', 
  '.' ]

- name: node
  entrypoint: npm
  args: ['run','create:env']
  env:
    - 'DATABASE_URL=${_DATABASE_URL}'

- name: node
  entrypoint: npx
  args: ['prisma','migrate','deploy']

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-east4-docker.pkg.dev/${PROJECT_ID}/imgs/${_SERVICE_NAME}:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  args: [gcloud,'run','deploy','sandlot-backend',
  '--image=us-east4-docker.pkg.dev/${PROJECT_ID}/imgs/${_SERVICE_NAME}:latest',
  '--region=us-east4']

timeout: "1600s"

